
title: "HS3 2025: 1st Workshop on Hardware-Supported Software Security"
description: "At ESORICS 2025, 25th of June 2025 in Toulouse, FR."

show_downloads: false
google_analytics:

author:
  name: Guillaume Hiet, Yuko Hara, Jan Tobias Muehlberg


# Dinky Theme: https://github.com/pages-themes/dinky
remote_theme: pages-themes/dinky@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown

